crud/views.py
from flask import Flask, render_template, request, redirect, url_for, Blueprint, session, Response, make_response
crud = Blueprint('crud', __name__)
from modules import SQLiteasy
from functools import wraps
from route import check_user

entries = {
    "created_by_user_name": {"type": "string", "notnull": True},
    "created_by_user_id": {"type": "string", "notnull": True},
    "title": {"type": "string", "notnull": True},
    "description": {"type": "string", "notnull": True},
    "content": {"type": "string", "notnull": True},
    "date": {"type": "string", "notnull": True},
    "post_id": {"type": "string", "notnull": True},
    "post_cover": {"type": "string", "notnull": True},
}

entries2 = {
    "user_email": {"type": "string", "notnull": True},
    "suscribed_to": {"type": "string", "notnull": True},
    "suscribed_from": {"type": "string", "notnull": True},
    "suscribed_date": {"type": "string", "notnull": True},
}

database = SQLiteasy("posts", entries)
database.create_database()

registers = SQLiteasy("registers", entries2)
registers.create_database()




#/change/add
@crud.route('/add')
@check_user # <- if there's no user on session this decorator send the user to register, its a blocker for non-registered users
def add():
    user = session.get("user")
    return render_template("./crud/index.html", user=user)

def get_user():
    return session.get('user', None)


def generate_id():
    import random
    a = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    return "".join(random.sample(a, 10))

@crud.route("/send", methods=["POST"])
def send():
    from user.views import users_db
    user_id = session.get("user_id")
    user_info = users_db.fetch_database_by("user_id", user_id)
    title = request.form.get("post_title")
    description = request.form.get("post_description")
    content = request.form.get("post_content")
    cover = request.form.get("post_cover")
    if not title and description and content and cover:
        return render_template("./extra/error.html", message="Fill all the inputs")
    else:
        database.insert_database(created_by_user_name=user_info[0][3], created_by_user_id=user_id, title=title, description=description, content=content, date="25-01-2025", post_id=generate_id(), post_cover=cover)
        return redirect(url_for('crud.admin'))



@crud.route("/update/<post_id>", methods=["POST"])
def update(post_id):
    from user.views import users_db
    user_id = session.get("user_id")
    user_info = users_db.fetch_database_by("user_id", user_id)
    title = request.form.get("post_title")
    description = request.form.get("post_description")
    content = request.form.get("post_content")
    cover = request.form.get("post_cover")

    if not title and description and content and cover:
        return render_template("./extra/error.html", message="Fill all the inputs")
    else:
        database.update_database_by("title", "post_id", post_id, title)
        database.update_database_by("description", "post_id", post_id, description)
        database.update_database_by("content", "post_id", post_id, content)
        database.update_database_by("post_cover", "post_id", post_id, cover)

        return redirect(url_for("crud.admin"))

@crud.route('/suscribe<user>')
def suscribe(user):
    return user


@crud.route("/admin")
@check_user # <- imported from route.py. It checks whether the user has a session logged in or not. if so it will call the below function, if not it will call for the register template
def admin():
    from user.views import users_db
    user_id = session.get("user_id")
    user_info = database.fetch_database_by("created_by_user_id", user_id)
    user = users_db.fetch_database_by("user_id", user_id)
    if user_info:
        print("hay user")
        return render_template("./crud/admin.html", data=user_info, user=user_id)
    else:
        print("no user")
        return render_template("./crud/admin.html", user=user_id)

@crud.route("/dashboard")
@check_user # <- imported from route.py. It checks whether the user has a session logged in or not. if so it will call the below function, if not it will call for the register template
def dashboard():
    from user.views import users_db
    user_id = session.get("user_id")
    user_info = database.fetch_database_by("created_by_user_id", user_id)
    user = users_db.fetch_database_by("user_id", user_id)
    if user_info:
        return render_template("./crud/admin_content.html", data=user_info, user=user_id)
    else:
        return render_template("./crud/admin_content.html", user=user_id)
    
@crud.route("/create")
@check_user # <- imported from route.py. It checks whether the user has a session logged in or not. if so it will call the below function, if not it will call for the register template
def create(): # <- Loads the create page
    user_id = session.get("user_id")
    if request.headers.get("HX-Request"):
        return render_template("./crud/index.html")
    else:
        return redirect(url_for('crud.admin'))

@crud.route("/stats")
@check_user # <- imported from route.py. It checks whether the user has a session logged in or not. if so it will call the below function, if not it will call for the register template
def stats():
    print("stats")
    user_id = session.get("user_id")
    from user.views import users_db
    data = database.fetch_database_by("created_by_user_id", user_id)
    if data:
        posts = len(data)
        all_registers = registers.fetch_database_by("suscribed_to", user_id)
        print(".,.,.,.,.,.,.")
        all_registers.sort(key=lambda x: x[-1], reverse=True)
        print(all_registers)
        print(".,.,.,.,.,.,.")
        visits = users_db.fetch_database_by("user_id", user_id)[0][5]
        return render_template("./crud/stats.html", all_registers=all_registers, visits=visits, posts=posts)
    else:
        return render_template("./crud/stats.html")
@crud.route("/edit/<post_id>")
@check_user
def edit(post_id):
    post_created_by = database.fetch_database_by("post_id", post_id)
    
    if post_created_by:
        creator = post_created_by[0][2] # <- it'll return the creator id of the fetched post 
    else:
        raise ValueError("Post not found")
    if creator == session.get("user_id"):
        if request.headers.get("HX-Request"):
            return render_template("./crud/edit.html", data=post_created_by)
        else:
            print("******")
            return redirect(url_for('crud.admin'))
    else:
        return ValueError("You don't have access to this section")

@crud.route("/delete/<post_id>")
@check_user
def delete(post_id):
    print(f"DELETE {post_id}")
    post_created_by = database.fetch_database_by("post_id", post_id)
    
    if post_created_by:
        creator = post_created_by[0][2] # <- it'll return the creator id of the fetched post 
    else:
        raise ValueError("Post not found")
    if creator == session.get("user_id"): # <- if the creator of the post is the same as the user logged in
        database.delete_database_row_by("post_id", post_id)
        return redirect(url_for('crud.admin'))
    else:   
        return ValueError("You don't have access to this section")

@crud.route("/profile")
@check_user
def profile():
    user_id = session.get("user_id")
    if user_id:
        from user.views import users_db
        posts = database.fetch_database_by("created_by_user_id", user_id) # returns all posts + id and name
        user_info = users_db.fetch_database_by("user_id", user_id) # it'll return email, name, password, id, visits, in that order
        return render_template("./crud/profile.html", posts=posts, user_info=user_info)
    else:
        raise ValueError("Something went wrong. Please contact us: Error code: 03")
    


    
    

user/views.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint
from modules import SQLiteasy
from crud.views import generate_id

user = Blueprint('user', __name__)

@user.route('/post/<post_id>')
def post(post_id):
    from crud.views import database
    from .test import convert
    from user.views import users_db
    data = database.fetch_database_by("post_id", post_id)
    user_id = data[0][2]
    user_info = users_db.fetch_database_by("user_id", user_id)
    content = convert(data[0][5])
    """ logica para añadir visit """
    from crud.views import database
    created_by = database.fetch_database_by("post_id", post_id)[0][2]
    current_visits = users_db.fetch_database_by("user_id", created_by)[0][5] + 1
    users_db.update_database_by("user_visits", "user_id", created_by, current_visits)
    return render_template("./user/post.html", data=data, content=content, user_info=user_info)

@user.route("/profile/<user_id>")
def profile(user_id):
    from user.views import users_db
    from crud.views import database
    user_info = users_db.fetch_database_by("user_id", user_id)
    return render_template("./user/profile.html", data=database.fetch_database_by("created_by_user_id", user_id), user_info=user_info)
    
    

@user.route("/suscribe/<user>")
def suscribe(user):
    from crud.views import database
    user_info = database.fetch_database_by("created_by", user)
    return render_template("./user/suscribe.html", data=user_info)

@user.route("/suscribed", methods=["POST"])
def suscribed():
    from crud.views import registers
    user_email = request.form.get("user_email")
    suscribed_to = request.form.get("suscribed_to")
    suscribed_from = request.form.get("suscribed_from")
    is_already_suscribed = registers.fetch_database_by_and("user_email", user_email, "suscribed_to", suscribed_to)
    print(".............")
    print(user_email)
    print(suscribed_to)
    print(suscribed_from)
    print(".............")
    if not is_already_suscribed:
        if user_email and suscribed_to:
            from datetime import datetime
            now = datetime.now()
            now_str = now.strftime('%Y-%m-%d %H:%M:%S')
            registers.insert_database(user_email=user_email, suscribed_to=suscribed_to, suscribed_from=suscribed_from, suscribed_date=now_str)
            return render_template("./extra/input.html", valid=True, message="You've suscribed!", value=user_email)
        else:
            raise ValueError("Something went wrong with the suscribe")
    else:
        return render_template("./extra/input.html", valid=False, message="You're already registered with this email", value=user_email)
    
user_entries = {
    "user_email": {"type": "string", "notnull": True},
    "user_name": {"type": "string", "notnull": True},
    "user_password": {"type": "string", "notnull": True},
    "user_id": {"type": "string", "notnull": True},
    "user_visits": {"type": "integer", "notnull": True},
    
}


users_db = SQLiteasy("users", user_entries)
users_db.create_database()

@user.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "POST":
        user_name = request.form.get("user_name")
        user_id = request.form.get("user_id")
        user_email = request.form.get("user_email")
        is_already_registered = users_db.fetch_database_by_or("user_email", user_email, "user_id", user_id)
        print("******************")
        print(user_name)
        print(user_id)
        print(user_email)
        print(is_already_registered)
        print("******************")
        if not is_already_registered:
            user_password = request.form.get("user_password")
            if len(user_email.split("@")[0]) < 5:
                return render_template('register.html', error="Use a real email address")
            users_db.insert_database(user_email=user_email, user_name=user_name, user_password=user_password, user_id=user_id, user_visits=0)
            session["user_id"] = user_id
            return redirect(url_for('crud.admin'))
        else:
            print("error")
            return render_template("register.html", error="This user is already register. Please login")
    else:
        return render_template("register.html")
    
@user.route("/login")
def login():
    return render_template('./login.html')

@user.route("/logged", methods=["POST"])
def logged():
    email_or_username = request.form.get("email_or_username")
    password = request.form.get("password")
    print("_______________-")
    print(email_or_username)
    print(password)
    print("_______________-")
    user = users_db.fetch_database_by("user_id", email_or_username)
    if user:
        current_pass = user[0][3]
        if current_pass == password:
            session["user_id"] = email_or_username
            return redirect(url_for("crud.admin"))
        else:
            return render_template("login.html", error="The password is not correct")
    else:
        return render_template("login.html", error="This account does not exists, create one please")

templates/crud/admin_content.html
{% if data %}
<h1>All posts:</h1>
<p>Edit, read, or delete your created posts</p>
<div class="cards flex flex-col gap-3">
    {% for post in data %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ post[8] }}" class="rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body d-flex flex-column h-100">
                    <div>
                        <h5 class="card-title">{{ post[3] }}</h5>
                        <p class="card-text">{{ post[4] }}</p>
                    </div>
                    <div class="mt-auto d-flex justify-content-end gap-2 pt-3">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">
                        Delete post
                    </button>
                        <a hx-get="{{url_for('crud.edit', post_id=post[7])}}" hx-target="#content"
                            class="btn btn-primary btn-sm">Edit post</a>
                        <a href="{{url_for('user.post', post_id=post[7])}}" class="btn btn-dark btn-sm">Read</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Delete post</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            This action cannot be undone
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary btn-sm" data-bs-dismiss="modal">Cancel</button>
                            <a href="{{url_for('crud.delete', post_id=post[7])}}" class="btn btn-dark btn-sm">Delete post</a>
                        </div>
                    </div>
                </div>
            </div>
{% endfor %}
{% else %}
<h1>All posts:</h1>
<p>You haven't created any post yet.</p>
{% endif %}

templates/crud/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap"
        rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.12"></script>

</head>

<body style="width: 90%; margin: auto; font-family: IBM Plex Sans;" class="">
    <div >
        <form action="{{url_for('crud.update', post_id=data[0][7])}}" method="post" id="main_form">
            <div class="flex justify-between items-center">
                <h1>Edit post</h1>
                <div>
                    <a href="{{url_for('crud.admin')}}" class="btn btn-secondary btn-sm mr-2">Cancel</a>
                    <button type="submit" class="btn btn-dark btn-sm" id="send_button">Save changes</button>
                </div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Post title</label>
                <input type="text" name="post_title" value="{{ data[0][3] }}" class="form-control" id="" required>
                <div id="emailHelp" class="form-text">Use a short and catchy one</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Post description</label>
                <input type="text" value="{{ data[0][4] }}" name="post_description" class="form-control" id="" required>
                <div id="emailHelp" class="form-text">Describe in a few words your post</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Post cover</label>
                <input type="text" value="{{ data[0][8] }}" name="post_cover" class="form-control" id="" required>
                <div id="emailHelp" class="form-text">Paste the image URL</div>
            </div>
    
            <label for="exampleInputEmail1" class="form-label">Post content</label>
            <div contenteditable="true" class="form-control p-2 w-full mb-3" style="min-height: 120px;"
                id="contenteditable">
                {{ data[0][5] | safe }}
            </div>
    
            <input type="text" class="form-control" id="img_url" placeholder="Post the image URL here">
            <button class="btn btn-dark mt-3" id="addImageButton">Add image</button>
            <input type="hidden" name="post_content" id="input_for_value">
        </form>
    </div>
    

    <script type="module">
        const contentEditable = document.getElementById('contenteditable');
        const imgUrl = document.getElementById('img_url');
        const addImageButton = document.getElementById('addImageButton');
        addImageButton.addEventListener('click', function (event) {
            event.preventDefault();
            const imgUrlValue = imgUrl.value;
            if (imgUrlValue) {
                const img = document.createElement('img');
                const gap = document.createElement('br');
                img.src = imgUrlValue;
                contentEditable.appendChild(img);
                contentEditable.appendChild(gap);
                imgUrl.value = ''; // Clear the input field after adding the image
            } else {
                alert('Please enter a valid image URL.');
            }
        })
        const sendButton = document.getElementById('send_button');
        const inputForValue = document.getElementById('input_for_value');
        sendButton.addEventListener('click', function (event) {
            getData()
        });
        function getData() {
            const content = contentEditable.innerHTML;
            console.log(content)
            inputForValue.value = content;
        }
    </script>

    <style>
        img {
            width: 200px;
            height: 200px;
            object-fit: cover;
        }

        .form-control:focus {
            border-color: black !important;
        }

        .form-control:focus {
            border-color: black !important;
            box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.25) !important;
        }
    </style>
</body>

</html>

templates/crud/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
<script src="https://unpkg.com/htmx.org@1.9.12"></script>

</head>
    
<body style="width: 90%; margin: auto; font-family: IBM Plex Sans;" class="">
    <form action="{{url_for('crud.send')}}" method="post" id="main_form">
        <div class="flex justify-between items-center">
            <h1>Create post</h1>
            <div>
                <a href="{{url_for('crud.admin')}}" class="btn btn-secondary btn-sm mr-2">Cancel</a>
                <button type="submit" class="btn btn-dark btn-sm" id="send_button">Create</button>
            </div>
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Post title</label>
            <input type="text" class="form-control" required name="post_title" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Use a short and catchy one</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Post description</label>
            <input type="text" class="form-control" required name="post_description" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Describe in a few words your post</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Post cover</label>
            <input type="text" class="form-control" required name="post_cover" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Paste the image URL</div>
        </div>

        <label for="exampleInputEmail1" class="form-label">Post content</label>
        <div contenteditable="true" required class="form-control p-2 w-full mb-3" style="min-height: 120px;" id="contenteditable">
    
        </div>

        <input type="text" class="form-control" id="img_url"  placeholder="Post the image URL here">
        <button class="btn btn-dark mt-3" id="addImageButton">Add image</button>
        <input type="hidden" name="post_content" id="input_for_value">
    </form>

    <script type="module">
        const contentEditable = document.getElementById('contenteditable');
        const imgUrl = document.getElementById('img_url');
        const addImageButton = document.getElementById('addImageButton');
        addImageButton.addEventListener('click', function(event){
            event.preventDefault();
            const imgUrlValue = imgUrl.value;
            if (imgUrlValue) {
                const img = document.createElement('img');
                const gap = document.createElement('br');
                img.src = imgUrlValue;
                contentEditable.appendChild(img);
                contentEditable.appendChild(gap);
                imgUrl.value = ''; // Clear the input field after adding the image
            } else {
                alert('Please enter a valid image URL.');
            }
        })
        const sendButton = document.getElementById('send_button');
        const inputForValue = document.getElementById('input_for_value');
        sendButton.addEventListener('click', function(event){
            getData()
        });
        function getData(){
            const content = contentEditable.innerHTML;
            console.log(content)
            inputForValue.value = content;
        }
    </script>

    <style>
        img{
            width: 200px;
            height: 200px;
            object-fit: cover;
        }
    </style>
</body>
</html>

templates/crud/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Post</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstdap@5.3.5/dist/css/bootstdap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap"
        rel="stylesheet">
</head>

<body style="width: 90%; height: 100vh; margin: auto; font-family: IBM Plex Sans;" class="">
    <h1>Profile settings</h1>
    {% if user_info %}  
        {% for item in user_info %}
        <div class="grid grid-cols-1 w-full gap-2 lg:grid-cols-2 lg:!gap-x-6">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Full name</label>
                <div class="input-group">
                    <div class="input-group-text">
                        <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                        </svg>
                    </div>
                    <input name="user_name" placeholder="" value="{{ item[2] }}" class="form-control"
                        id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div id="emailHelp" class="form-text">This will be public in every of your posts</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <div class="input-group ">
                    <div class="input-group-text">
                        <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                        </svg>
                    </div>
                    <input name="user_email" value="{{ item[1] }}" class="form-control"
                        id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div id="emailHelp" class="form-text">If you decide, users could contact you.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Password</label>
                <div class="input-group">
                    <div class="input-group-text">
                        <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                        </svg>
                    </div>
                    <input name="user_password" class="form-control" id="exampleInputEmail1"
                        value="{{ item[3] }}" aria-describedby="emailHelp">
                </div>
                <div id="emailHelp" class="form-text">Use a secure password</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Create an User ID</label>
                <div class="input-group">
                    <div class="input-group-text">
                        <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M7.864 4.243A7.5 7.5 0 0 1 19.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 0 0 4.5 10.5a7.464 7.464 0 0 1-1.15 3.993m1.989 3.559A11.209 11.209 0 0 0 8.25 10.5a3.75 3.75 0 1 1 7.5 0c0 .527-.021 1.049-.064 1.565M12 10.5a14.94 14.94 0 0 1-3.6 9.75m6.633-4.596a18.666 18.666 0 0 1-2.485 5.33" />
                        </svg>
                    </div>
                    <input name="user_id" value="{{ item[4] }}" class="form-control" disabled id="exampleInputEmail1"
                        aria-describedby="emailHelp">
                </div>
                <div id="emailHelp" class="form-text">Unique indentifier, cannot be changed.</div>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <p>Something went wrong. Error code: 03</p>
    {% endif %}

</body>

</html>