user/views.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint
from modules import SQLiteasy
from crud.views import generate_id

user = Blueprint('user', __name__)

@user.route('/post/<post_id>')
def post(post_id):
    from crud.views import database
    from .test import convert
    from user.views import users_db
    data = database.fetch_database_by("post_id", post_id)
    user_id = data[0][2]
    user_info = users_db.fetch_database_by("user_id", user_id)
    content = convert(data[0][5])
    """ logica para añadir visit """
    from crud.views import database
    created_by = database.fetch_database_by("post_id", post_id)[0][2]
    current_visits = users_db.fetch_database_by("user_id", created_by)[0][5] + 1
    users_db.update_database_by("user_visits", "user_id", created_by, current_visits)
    return render_template("./user/post.html", data=data, content=content, user_info=user_info)

@user.route("/profile/<user_id>")
def profile(user_id):
    from user.views import users_db
    from crud.views import database
    user_info = users_db.fetch_database_by("user_id", user_id)
    return render_template("./user/profile.html", data=database.fetch_database_by("created_by_user_id", user_id), user_info=user_info)
    
    

@user.route("/suscribe/<user>")
def suscribe(user):
    from crud.views import database
    user_info = database.fetch_database_by("created_by", user)
    return render_template("./user/suscribe.html", data=user_info)

@user.route("/suscribed", methods=["POST"])
def suscribed():
    from crud.views import registers
    user_email = request.form.get("user_email")
    suscribed_to = request.form.get("suscribed_to")
    suscribed_from = request.form.get("suscribed_from")
    is_already_suscribed = registers.fetch_database_by_and("user_email", user_email, "suscribed_to", suscribed_to)
    print(".............")
    print(user_email)
    print(suscribed_to)
    print(suscribed_from)
    print(".............")
    if not is_already_suscribed:
        if user_email and suscribed_to:
            from datetime import datetime
            now = datetime.now()
            now_str = now.strftime('%Y-%m-%d %H:%M:%S')
            registers.insert_database(user_email=user_email, suscribed_to=suscribed_to, suscribed_from=suscribed_from, suscribed_date=now_str)
            return render_template("./extra/input.html", valid=True, message="You've suscribed!", value=user_email)
        else:
            raise ValueError("Something went wrong with the suscribe")
    else:
        return render_template("./extra/input.html", valid=False, message="You're already registered with this email", value=user_email)
    
user_entries = {
    "user_email": {"type": "string", "notnull": True},
    "user_name": {"type": "string", "notnull": True},
    "user_password": {"type": "string", "notnull": True},
    "user_id": {"type": "string", "notnull": True},
    "user_visits": {"type": "integer", "notnull": True},
    
}


users_db = SQLiteasy("users", user_entries)
users_db.create_database()

@user.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "POST":
        user_name = request.form.get("user_name")
        user_id = request.form.get("user_id")
        user_email = request.form.get("user_email")
        is_already_registered = users_db.fetch_database_by_or("user_email", user_email, "user_id", user_id)
        print("******************")
        print(user_name)
        print(user_id)
        print(user_email)
        print(is_already_registered)
        print("******************")
        if not is_already_registered:
            user_password = request.form.get("user_password")
            if len(user_email.split("@")[0]) < 5:
                return render_template('register.html', error="Use a real email address")
            users_db.insert_database(user_email=user_email, user_name=user_name, user_password=user_password, user_id=user_id, user_visits=0)
            session["user_id"] = user_id
            return redirect(url_for('crud.admin'))
        else:
            print("error")
            return render_template("register.html", error="This user is already register. Please login")
    else:
        return render_template("register.html")
    
@user.route("/login")
def login():
    return render_template('./login.html')

@user.route("/logged", methods=["POST"])
def logged():
    email_or_username = request.form.get("email_or_username")
    password = request.form.get("password")
    print("_______________-")
    print(email_or_username)
    print(password)
    print("_______________-")
    user = users_db.fetch_database_by("user_id", email_or_username)
    if user:
        current_pass = user[0][3]
        if current_pass == password:
            session["user_id"] = email_or_username
            return redirect(url_for("crud.admin"))
        else:
            return render_template("login.html", error="The password is not correct")
    else:
        return render_template("login.html", error="This account does not exists, create one please")

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>


</head>


<body style="font-family: DM Sans;">
    <div class="w-[90%] h-screen flex justify-center items-center m-auto py-4">
        <div class="grid grid-cols-1 h-full w-[90%] p-4 lg:grid-cols-2">
            <div class="overflow-hidden flex justify-center hidden lg:block">
                <img src="{{url_for('static', filename='img/phone.png.png')}}" class="h-full" alt="">
            </div>
            <div class="h-full relative ">
                <h1>Welcome back!</h1>
                <p>Continue sharing your thoughts, analysis, and more...</p>
                <form action="{{url_for('user.logged')}}" method="post">
                    {% if error %}
                    <!-- Username -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">User ID</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M7.864 4.243A7.5 7.5 0 0 1 19.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 0 0 4.5 10.5a7.464 7.464 0 0 1-1.15 3.993m1.989 3.559A11.209 11.209 0 0 0 8.25 10.5a3.75 3.75 0 1 1 7.5 0c0 .527-.021 1.049-.064 1.565M12 10.5a14.94 14.94 0 0 1-3.6 9.75m6.633-4.596a18.666 18.666 0 0 1-2.485 5.33" />
                                </svg>
                            </div>
                            <input placeholder="@jarias123" name="email_or_username" class="form-control is-invalid" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">Use your unique user ID.</div>
                    </div>
                    <!-- Username -->
                    <!-- Password -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Password</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                                </svg>
                            </div>
                            <input  name="password" placeholder="secret123" class="form-control is-invalid" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">
                            Did you forget it?
                            <a href="" class="link link-dark">Recover my password</a>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark w-full">Login</button>
                    <div id="emailHelp" class="form-text text-danger">{{ error }}</div>
                    <!-- Password -->
                    {% else %}
                    <!-- Username -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">User ID</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M7.864 4.243A7.5 7.5 0 0 1 19.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 0 0 4.5 10.5a7.464 7.464 0 0 1-1.15 3.993m1.989 3.559A11.209 11.209 0 0 0 8.25 10.5a3.75 3.75 0 1 1 7.5 0c0 .527-.021 1.049-.064 1.565M12 10.5a14.94 14.94 0 0 1-3.6 9.75m6.633-4.596a18.666 18.666 0 0 1-2.485 5.33" />
                                </svg>
                            </div>
                            <input  name="email_or_username" placeholder="@jarias123" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">Use your unique user ID.</div>
                    </div>
                    <!-- Username -->
                    <!-- Password -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Password</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                                </svg>
                            </div>
                            <input name="password" placeholder="@jarias123"  class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">
                            Did you forget it?
                            <a href="" class="link link-dark">Recover my password</a>
                        </div>
                    </div>
                    <!-- Password -->
                    <button type="submit" class="btn btn-dark w-full">Login</button>
                    {% endif %}

                    <p class="w-full text-center absolute bottom-0">Don't have an account? <a href="{{url_for('user.register')}}" class="link link-dark">Create an account</a></p>
                </form>
            </div>
        </div>
        <style>
            .form-control:focus {
                border-color: black !important;
            }

            .form-control:focus {
                border-color: black !important;
                box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.25) !important;
            }
        </style>
    </div>

</body>

</html>

templates/main.html
hola

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>


</head>


<body style="font-family: DM Sans;">
    <div class="w-[90%] h-screen flex justify-center items-center m-auto py-4">
        <div class="grid grid-cols-1 h-full w-[90%] p-4 lg:grid-cols-2">
            <div class="overflow-hidden flex justify-center hidden lg:block">
                <img src="{{url_for('static', filename='img/phone.png.png')}}" class="h-full" alt="">
            </div>
            <div class="h-full relative ">
                <h1>Create an account</h1>
                <p>Start sharing your thougts, analysis, and more...</p>
                <form action="{{url_for('user.register')}}" method="post">
                    {% if error %}

                    <div class="grid grid-cols-1 gap-2 lg:grid-cols-2">
                        <!-- email input name -->
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Full name</label>
                            <div class="input-group">
                                <div class="input-group-text">
                                    <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                                    </svg>
                                </div>
                                <input placeholder="Josué Arias" name="user_name" class="form-control is-invalid"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                            <div id="emailHelp" class="form-text">This will be public in every of your posts</div>
                        </div>
                        <!-- email input name ends -->
                        <!-- email input -->
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email address</label>
                            <div class="input-group ">
                                <div class="input-group-text">
                                    <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                                    </svg>
                                </div>
                                <input name="user_email" placeholder="jarias@gmail.com" class="form-control is-invalid"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                            <div id="emailHelp" class="form-text">If you decide, users could contact you.</div>
                        </div>
                        <!-- email input end -->

                    </div>

                    <!--  input username -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Create an User ID</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M7.864 4.243A7.5 7.5 0 0 1 19.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 0 0 4.5 10.5a7.464 7.464 0 0 1-1.15 3.993m1.989 3.559A11.209 11.209 0 0 0 8.25 10.5a3.75 3.75 0 1 1 7.5 0c0 .527-.021 1.049-.064 1.565M12 10.5a14.94 14.94 0 0 1-3.6 9.75m6.633-4.596a18.666 18.666 0 0 1-2.485 5.33" />
                                </svg>
                            </div>
                            <input name="user_id" placeholder="@jarias123" class="form-control is-invalid" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text  text-danger">Unique indentifier, cannot be changed.</div>
                    </div>
                    <!-- input username  ends -->

                    <!--  input password -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Password</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                                </svg>
                            </div>
                            <input name="user_password" class="form-control is-invalid" id="exampleInputEmail1"
                                placeholder="secret123" aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">Use a secure password</div>
                    </div>
                    <!--  input password ends -->

                    <button class="btn btn-dark w-full">Create account</button>
                    <div id="emailHelp" class="form-text text-danger">{{ error }}</div>

                    {% else %}

                    <div class="grid grid-cols-1 gap-2 lg:grid-cols-2">
                        <!-- email input name -->
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Full name</label>
                            <div class="input-group">
                                <div class="input-group-text">
                                    <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                                    </svg>
                                </div>
                                <input name="user_name" placeholder="Josué Arias" class="form-control"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                            <div id="emailHelp" class="form-text">This will be public in every of your posts</div>
                        </div>
                        <!-- email input name ends -->
                        <!-- email input -->
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email address</label>
                            <div class="input-group ">
                                <div class="input-group-text">
                                    <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                        viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                                    </svg>
                                </div>
                                <input name="user_email" placeholder="jarias@gmail.com" class="form-control"
                                    id="exampleInputEmail1" aria-describedby="emailHelp">
                            </div>
                            <div id="emailHelp" class="form-text">If you decide, users could contact you.</div>
                        </div>
                        <!-- email input end -->

                    </div>
                    <!-- email input username -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Create an User ID</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M7.864 4.243A7.5 7.5 0 0 1 19.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 0 0 4.5 10.5a7.464 7.464 0 0 1-1.15 3.993m1.989 3.559A11.209 11.209 0 0 0 8.25 10.5a3.75 3.75 0 1 1 7.5 0c0 .527-.021 1.049-.064 1.565M12 10.5a14.94 14.94 0 0 1-3.6 9.75m6.633-4.596a18.666 18.666 0 0 1-2.485 5.33" />
                                </svg>
                            </div>
                            <input name="user_id" placeholder="@jarias123" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">Unique indentifier, cannot be changed.</div>
                    </div>
                    <!-- email input username  ends -->
                    <!-- email input password -->
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Password</label>
                        <div class="input-group">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                                </svg>
                            </div>
                            <input name="user_password" class="form-control" id="exampleInputEmail1"
                                placeholder="secret123" aria-describedby="emailHelp">
                        </div>
                        <div id="emailHelp" class="form-text">Use a secure password</div>
                    </div>
                    <!-- email input password ends -->

                    <button class="btn btn-dark w-full">Create account</button>
                    {% endif %}
                    <p class="w-full text-center absolute bottom-0">Already have an account? <a href="{{url_for('user.login')}}"
                        class="link link-dark">Login</a></p>
                </form>


            </div>
        </div>
        <style>
            .form-control:focus {
                border-color: black !important;
            }

            .form-control:focus {
                border-color: black !important;
                box-shadow: 0 0 0 0.25rem rgba(0, 0, 0, 0.25) !important;
            }
        </style>
    </div>

</body>

</html>