user/views.py
from flask import Flask, render_template, request, redirect, url_for, session, Blueprint
from modules import SQLiteasy
from crud.views import generate_id

user = Blueprint('user', __name__)

@user.route('/post/<post_id>')
def post(post_id):
    from crud.views import database
    from .test import convert
    from user.views import users_db
    data = database.fetch_database_by("post_id", post_id)
    user_id = data[0][2]
    user_info = users_db.fetch_database_by("user_id", user_id)
    content = convert(data[0][5])
    """ logica para añadir visit """
    from crud.views import database
    created_by = database.fetch_database_by("post_id", post_id)[0][2]
    current_visits = users_db.fetch_database_by("user_id", created_by)[0][5] + 1
    users_db.update_database_by("user_visits", "user_id", created_by, current_visits)
    return render_template("./user/post.html", data=data, content=content, user_info=user_info)

@user.route("/profile/<user_id>")
def profile(user_id):
    from user.views import users_db
    from crud.views import database
    user_info = users_db.fetch_database_by("user_id", user_id)
    return render_template("./user/profile.html", data=database.fetch_database_by("created_by_user_id", user_id), user_info=user_info)
    
    

@user.route("/suscribe/<user>")
def suscribe(user):
    from crud.views import database
    user_info = database.fetch_database_by("created_by", user)
    return render_template("./user/suscribe.html", data=user_info)

@user.route("/suscribed", methods=["POST"])
def suscribed():
    from crud.views import registers
    user_email = request.form.get("user_email")
    suscribed_to = request.form.get("suscribed_to")
    suscribed_from = request.form.get("suscribed_from")
    is_already_suscribed = registers.fetch_database_by_and("user_email", user_email, "suscribed_to", suscribed_to)
    print(".............")
    print(user_email)
    print(suscribed_to)
    print(suscribed_from)
    print(".............")
    if not is_already_suscribed:
        if user_email and suscribed_to:
            from datetime import datetime
            now = datetime.now()
            now_str = now.strftime('%Y-%m-%d %H:%M:%S')
            registers.insert_database(user_email=user_email, suscribed_to=suscribed_to, suscribed_from=suscribed_from, suscribed_date=now_str)
            return render_template("./extra/input.html", valid=True, message="You've suscribed!", value=user_email)
        else:
            raise ValueError("Something went wrong with the suscribe")
    else:
        return render_template("./extra/input.html", valid=False, message="You're already registered with this email", value=user_email)
    
user_entries = {
    "user_email": {"type": "string", "notnull": True},
    "user_name": {"type": "string", "notnull": True},
    "user_password": {"type": "string", "notnull": True},
    "user_id": {"type": "string", "notnull": True},
    "user_visits": {"type": "integer", "notnull": True},
    
}


users_db = SQLiteasy("users", user_entries)
users_db.create_database()

@user.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "POST":
        user_name = request.form.get("user_name")
        user_id = request.form.get("user_id")
        user_email = request.form.get("user_email")
        is_already_registered = users_db.fetch_database_by_or("user_email", user_email, "user_id", user_id)
        print("******************")
        print(user_name)
        print(user_id)
        print(user_email)
        print(is_already_registered)
        print("******************")
        if not is_already_registered:
            user_password = request.form.get("user_password")
            if len(user_email.split("@")[0]) < 5:
                return render_template('register.html', error="Use a real email address")
            users_db.insert_database(user_email=user_email, user_name=user_name, user_password=user_password, user_id=user_id, user_visits=0)
            session["user_id"] = user_id
            return redirect(url_for('crud.admin'))
        else:
            print("error")
            return render_template("register.html", error="This user is already register. Please login")
    else:
        return render_template("register.html")
    
@user.route("/login")
def login():
    return render_template('./login.html')

@user.route("/logged", methods=["POST"])
def logged():
    email_or_username = request.form.get("email_or_username")
    password = request.form.get("password")
    print("_______________-")
    print(email_or_username)
    print(password)
    print("_______________-")
    user = users_db.fetch_database_by("user_id", email_or_username)
    if user:
        current_pass = user[0][3]
        if current_pass == password:
            session["user_id"] = email_or_username
            return redirect(url_for("crud.admin"))
        else:
            return render_template("login.html", error="The password is not correct")
    else:
        return render_template("login.html", error="This account does not exists, create one please")

templates/user/post.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Post</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link
        href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
        rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap"
        rel="stylesheet">
        <script src="https://unpkg.com/htmx.org@1.9.10"></script>
    </head>


<body style="width: 90%; height: 100vh; margin: auto; font-family: IBM Plex Sans;" class="">
    <div class="mt-4">
        {% for post in data %}
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item text-sm"><a href="{{url_for('user.profile', user_id=post[2])}}"
                        class="link link-dark">@{{ post[2] }}</a></li>
                <li class="breadcrumb-item text-sm" aria-current="page">{{ post[3] }}</li>
            </ol>
        </nav>
        <h2>{{ post[3] }}</h2>
        <p class="text-sm">Por:
            <a href="{{url_for('user.profile', user_id=post[2])}}" class="link link-dark "> {{ user_info[0][2] }}</a>
        </p>
        <h5>{{ post[4] }}</h5>
        <p>{{ content | safe }}</p>
        <hr>
        <div class="card !border-none">
            <div class="card-body  !p-0">
                <h5 class="card-title">Suscríbete a {{ user_info[0][2] }}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">Para recibir información, noticias, analisis</h6>
                <form hx-post="{{url_for('user.suscribed')}}" hx-target="#content_form">
                    <div class="mb-3" id="content_form">
                        <label for="exampleInputEmail1" class="form-label">Correo electrónico</label>
                        <div class="input-group" id="">
                            <div class="input-group-text">
                                <svg class="h-5 w-5 opacity-50" xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
                                </svg>
                            </div>
                            <input name="user_email" placeholder="jarias@gmail.com" class="form-control"
                                id="exampleInputEmail1" aria-describedby="emailHelp">
                            <button class="btn btn-sm btn-dark" type="submit">Suscribirme</button>
                        </div>
                        <div id="emailHelp" class="form-text">A este correo te enviaré notas, información, analisis, sobre temas nacionales, y económicos.</div>
                    </div>
                    <input type="hidden" name="suscribed_to" value="{{ post[2] }}">
                    <input type="hidden" name="suscribed_from" value="{{ post[3] }}">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <style>
        img {
            width: 100%;
            height: 200px;
            object-fit: cover;
            border-radius: 6px;
        }

        @media screen and (min-width: 1024px) {

            /* Estilos solo para pantallas de PC (desde 1024px en adelante) */
            img {
                width: 70%;
                height: 450px;
            }
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>


</body>

</body>

</html>

templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Title</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
            rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap"
            rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap"
            rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    </head>
    
<body style="width: 90%; margin: auto; font-family: Space Grotesk;" class="">
    <div class="p-4 my-2">
        <h2 class="text-3xl font-medium">{{ user_info[0][2] }}</h2>
        <p class="font-base">User's recent posts:</p>
    {% if data %}
    {% for post in data %}
    <div class="card card-side bg-base-100 shadow-sm w-full h-52 mb-2">
        <figure>
            <img src="{{ post[8] }}" class="w-86" alt="Movie" />
        </figure>
        <div class="card-body">
            <h2 class="card-title">{{ post[3] }}</h2>
            <p>{{ post[4] }}</p>
            <div class="card-actions justify-end">
                <a href="{{url_for('user.post', post_id=post[7])}}" class="btn btn-neutral">Read</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>This user has not created any post yet</a></p>
    {% endif %}
    </div>

</body>
</html>

templates/user/suscribe.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">
</head>


<body style="width: 90%; height: 100vh; margin: auto; font-family: Inter;" class="my-4">
    <div class="card my-4" style="padding: 0px; border: none;">
        <div class="card-body" style="padding: 0px; border: none;">
            <h2 class="card-title">Suscríbete</h2>
            <p class="card-text">Obtén información sobre economía, y temas nacionales en tu correo semanalmente</p>
            <form action="{{url_for('user.suscribed')}}" method="post">
                <div class="mb-3">
                    <label class="form-label">Correo electrónico</label>
                    <input  type="text" name="user_email" class="form-control" id="">
                    <input  type="hidden" value="{{ data[0][1] }}" name="suscribed_to" class="form-control" id="">
                    <div class="form-text">A este correo te enviaré los analisís y noticias semalmente, <strong>totalmente gratis</strong></div>
                </div>
                <button class="btn btn-sm btn-dark">Suscribirme</button>
            </form>
        </div>
    </div>
    <p>Post para leer:</p>
    {% for post in data %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ post[7] }}" style="height: 200px; width: 100%; object-fit: cover;" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ post[2] }}</h5>
                    <p class="card-text">{{ post[3] }}</p>
                    <a class="btn btn-dark mt-3" href="{{url_for('user.post', post_id=post[6])}}">Leer post</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <style>
        img {
            width: 100%;
            height: 200px;
            object-fit: cover;
            border-radius: 12px;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>


</body>

</body>

</html>